config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('temp_control.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

temp_control/urls.py
from django.urls import path
from temp_control import views
from django.views.generic import RedirectView

app_name = 'temp_control'

urlpatterns = [
    path('', RedirectView.as_view(url='/temp-control/')),
    # views for template
    path('temp-control/', views.index, name='room_info'),
    path('temp-control/cooler/toggle/',views.cooler_toggle ,name="cooler_toggle"),
    path('temp-control/heater/toggle/',views.heater_toggle ,name="heater_toggle"),
    path('temp-control/mode/toggle/',views.automatic_toggle ,name="automatic_toggle"),
    #views for API,
    path("api/temp-control/", views.room_info),
    path("api/temp-control/cooler/toggle/", views.cooler_toggle_API),
    path("api/temp-control/heater/toggle/", views.heater_toggle_API),
    path("api/temp-control/mode/toggle/", views.automatic_toggle_API),

]

temp_control/models.py
from django.db import models


class Room(models.Model):
    cooler_status = models.BooleanField(default=False)
    heater_status = models.BooleanField(default=False)
    is_automatic = models.BooleanField(default=False)


class Weather(models.Model):
    city_temperature = models.IntegerField()
    city_weather_condition = models.CharField(max_length=200)

temp_control/views.py
from django.shortcuts import render, redirect
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view

from .models import Room, Weather

from modules.rpiModules import get_temperature, cooler_turn_on, cooler_turn_off, heater_turn_on, heater_turn_off


def index(request):
    room = Room.objects.get(pk=1)
    weather = Weather.objects.get()
    temperature = get_temperature()
    context = {
        'city_temperature': weather.city_temperature,
        'city_weather_condition': weather.city_weather_condition,
        'temperature': temperature,
        'room': room
    }
    return render(request, 'temp_control/index.html', context)


def cooler_toggle(request):
    room = Room.objects.get(pk=1)
    if not room.is_automatic:
        if room.cooler_status:
            cooler_turn_off()
            room.cooler_status = False
            room.save()

        else:
            cooler_turn_on()
            room.cooler_status = True
            room.save()

    return redirect('temp_control:room_info')


def heater_toggle(request):
    room = Room.objects.get(pk=1)
    if not room.is_automatic:
        if room.heater_status:
            heater_turn_off()
            room.heater_status = False
            room.save()

        else:
            heater_turn_on()
            room.heater_status = True
            room.save()

    return redirect('temp_control:room_info')


def automatic_toggle(request):
    room = Room.objects.get(pk=1)
    if room.is_automatic:
        room.is_automatic = False
        room.save()
    else:
        room.is_automatic = True
        heater_turn_off()
        cooler_turn_off()
        room.cooler_status = False
        room.heater_status = False
        room.save()
    return redirect('temp_control:room_info')


@api_view(['GET'])
def room_info(request):

    room = Room.objects.get(id=1)
    context = {
        'temperature': get_temperature(),
        'is_automatic': room.is_automatic,
        'cooler_status': room.cooler_status,
        'heater_status': room.heater_status,
    }
    return Response(context)


@api_view(['GET'])
def cooler_toggle_API(request):
    room = Room.objects.get(pk=1)
    if not room.is_automatic:
        if room.cooler_status:
            cooler_turn_off()
            room.cooler_status = False
            room.save()
            print('cooler is off')
            content = {"detail": "cooler OFF"}
            return Response(content)

        else:
            cooler_turn_on()
            room.cooler_status = True
            room.save()
            print('cooler is on')
            content = {"detail": "cooler ON"}
            return Response(content)

    else:
        content = {'detail': 'System is on automatic mode!'}

        return Response(content, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET'])
def heater_toggle_API(request):
    room = Room.objects.get(pk=1)
    if not room.is_automatic:
        if room.heater_status:
            heater_turn_off()
            room.heater_status = False
            room.save()
            print('heater is off')
            content = {"detail": "heater OFF"}
            return Response(content)

        else:
            heater_turn_on()
            room.heater_status = True
            room.save()
            print('heater is on')
            content = {"detail": "heater ON"}
            return Response(content)

    else:
        content = {'detail': 'System is on automatic mode!'}

        return Response(content, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET'])
def automatic_toggle_API(request):
    room = Room.objects.get(pk=1)
    if room.is_automatic:
        room.is_automatic = False
        room.save()
        content = {'detail': 'system is on manual mode'}

        return Response(content)
    else:
        room.is_automatic = True
        heater_turn_off()
        cooler_turn_off()
        room.cooler_status = False
        room.heater_status = False
        room.save()
        content = {'detail': 'system is on automatic mode'}

        return Response(content)

temp_control/templates/temp_control/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Temperature control</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- Font Awesome -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
rel="stylesheet"
/>
<!-- Google Fonts -->
<link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/>
<!-- MDB -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.0/mdb.min.css"
rel="stylesheet"
/>
<style>
  a { color: inherit; } 
  a:hover {
    color:#00A0C6; 
    text-decoration:none; 
    cursor:pointer;  
}
a, u {
  text-decoration: none;
}
</style>
</head>
<body>
  {% load static %}
  <section class="vh-100" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-8 col-lg-6 col-xl-4">
  
          <div class="card" style="border-radius: 10px;">
            <div class="bg-image " style="border-top-left-radius: 10px; border-top-right-radius: 10px;">
              <img src="{% static 'temp_control/background.jpg' %}"
                class="w-100" />
              <div class="mask" style="background-color:  rgba(0,0,0,.45)">

                <div class="text-center text-white">
                  <p class="h3 mb-4">{{city_weather_condition}}</p>
                  <p class="h5 mb-2">Your City</p>
                  <p class="display-2"><strong>{{city_temperature}} °C</strong> </p>
                </div>
              </div>
            </div>
            
            <div class="card-body p-4 text-center">

              <div class="d-flex justify-content-center bd-highlight mb-3">
                <div class="h5 bd-highlight mx-2"> Automatic </div>
                
                <div class="form-check form-switch">
                  <a href="{% url 'temp_control:automatic_toggle' %}">
                    <input class="form-check-input" type="checkbox" role="switch" {% if room.is_automatic %}checked {% endif %}> 
                  </a>
                </div>
               
              </div>
              <div class="d-flex bd-highlight mb-3">
                <div class="me-auto h5 bd-highlight">Room Temperature</div>
                <div class="h5 bd-highlight">
                  {{temperature}}°C
                  <svg xmlns="http://www.w3.org/2000/svg" width="25" fill="currentColor" class="bi bi-thermometer-half" viewBox="0 0 16 16">
                    <path d="M9.5 12.5a1.5 1.5 0 1 1-2-1.415V6.5a.5.5 0 0 1 1 0v4.585a1.5 1.5 0 0 1 1 1.415z"/>
                    <path d="M5.5 2.5a2.5 2.5 0 0 1 5 0v7.55a3.5 3.5 0 1 1-5 0V2.5zM8 1a1.5 1.5 0 0 0-1.5 1.5v7.987l-.167.15a2.5 2.5 0 1 0 3.333 0l-.166-.15V2.5A1.5 1.5 0 0 0 8 1z"/>
                  </svg>
                </div>
              </div>

            
              <div class="d-flex bd-highlight mb-3">
                <div class="h5 bd-highlight">
                  {% if not room.is_automatic %}
                  <div class="form-check form-switch">
                    <a href="{% url 'temp_control:cooler_toggle' %}">
                    <input class="form-check-input" type="checkbox" role="switch" {% if room.cooler_status %}checked {% else %} {% endif %}> 
                  </a>
                </div>
                  {% endif %}
                  
                </div>
                <div class="h5 bd-highlight">
                  <svg xmlns="http://www.w3.org/2000/svg" width="25" fill="{% if room.cooler_status %}#3C99DC{% endif %}" class="bi bi-wind" viewBox="0 0 16 16">
                    <path d="M12.5 2A2.5 2.5 0 0 0 10 4.5a.5.5 0 0 1-1 0A3.5 3.5 0 1 1 12.5 8H.5a.5.5 0 0 1 0-1h12a2.5 2.5 0 0 0 0-5zm-7 1a1 1 0 0 0-1 1 .5.5 0 0 1-1 0 2 2 0 1 1 2 2h-5a.5.5 0 0 1 0-1h5a1 1 0 0 0 0-2zM0 9.5A.5.5 0 0 1 .5 9h10.042a3 3 0 1 1-3 3 .5.5 0 0 1 1 0 2 2 0 1 0 2-2H.5a.5.5 0 0 1-.5-.5z"/>
                  </svg>
                </div>
                <div class="ms-auto h5 bd-highlight">{% if room.cooler_status %} ON {% else %} OFF {% endif %}</div>
              </div>


              <div class="d-flex bd-highlight mb-3">
                <div class="h5 bd-highlight">
                  {% if not room.is_automatic %}

                    <div class="form-check form-switch">
                        <a href="{% url 'temp_control:heater_toggle' %}">
                        <input class="form-check-input" type="checkbox" role="switch" {% if room.heater_status %}checked {% else %} {% endif %}>
                      </a> 
                    </div>
                  {% endif %}
                </div>
                <div class="h5 bd-highlight">
                  <svg xmlns="http://www.w3.org/2000/svg" width="25" fill="{% if room.heater_status %}#FF3F00{% endif %}" class="bi bi-fire" viewBox="0 0 16 16">
                    <path d="M8 16c3.314 0 6-2 6-5.5 0-1.5-.5-4-2.5-6 .25 1.5-1.25 2-1.25 2C11 4 9 .5 6 0c.357 2 .5 4-2 6-1.25 1-2 2.729-2 4.5C2 14 4.686 16 8 16Zm0-1c-1.657 0-3-1-3-2.75 0-.75.25-2 1.25-3C6.125 10 7 10.5 7 10.5c-.375-1.25.5-3.25 2-3.5-.179 1-.25 2 1 3 .625.5 1 1.364 1 2.25C11 14 9.657 15 8 15Z"/>
                  </svg>
                </div>
                <div class="ms-auto h5 bd-highlight">{% if room.heater_status %} ON {% else %} OFF {% endif %}</div>
              </div>
              
              
              
            </div>
          </div>
  
        </div>
      </div>
    </div>
  </section>
  <!-- MDB -->
<script
type="text/javascript"
src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.0/mdb.min.js"
></script>

</body>
</html>